<a href="https://colab.research.google.com/github/LucanMarques89/LucanMarques89/blob/main/Dados_PRF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
origem01 = '/content/drive/My Drive/Data/PRF/2024/'
origem02 = '/content/drive/My Drive/Data/PRF/2025/'
origem03 = '/content/drive/My Drive/Data/PRF/2026/'

In [ ]:
acidentes_todas_causas_tipos24 = origem01 + 'acidentes2024_todas_causas_tipos.csv'
acidentes_todas_causas_tipos25 = origem02 + 'acidentes2025_todas_causas_tipos.csv'
acidentes_todas_causas_tipos26 = origem03 + 'acidentes2026_todas_causas_tipos.csv'

acidentes24 = origem01 + 'acidentes2024.csv'
acidentes25 = origem02 + 'acidentes2025.csv'
acidentes26 = origem03 + 'acidentes2026.csv'

datatran24 = origem01 + 'datatran2024.csv'
datatran25 = origem02 + 'datatran2025.csv'
datatran26 = origem03 + 'datatran2026.csv'

In [ ]:
acidentes_todas_causas_tipos24 = pd.read_csv(acidentes_todas_causas_tipos24, low_memory=False, sep=';', encoding='latin1')
acidentes_todas_causas_tipos25 = pd.read_csv(acidentes_todas_causas_tipos25, low_memory=False, sep=';', encoding='latin1')
acidentes_todas_causas_tipos26 = pd.read_csv(acidentes_todas_causas_tipos26, low_memory=False, sep=';', encoding='latin1')

acidentes24 = pd.read_csv(acidentes24, low_memory=False, sep=';', encoding='latin1')
acidentes25 = pd.read_csv(acidentes25, low_memory=False, sep=';', encoding='latin1')
acidentes26 = pd.read_csv(acidentes26, low_memory=False, sep=';', encoding='latin1')

datatran24 = pd.read_csv(datatran24, low_memory=False, sep=';', encoding='latin1')
datatran25 = pd.read_csv(datatran25, low_memory=False, sep=';', encoding='latin1')
datatran26 = pd.read_csv(datatran26, low_memory=False, sep=';', encoding='latin1')

In [ ]:
acidentes_todas_causas_tipos24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603215 entries, 0 to 603214
Data columns (total 37 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      603215 non-null  float64
 1   pesid                   545574 non-null  float64
 2   data_inversa            603215 non-null  object
 3   dia_semana              603215 non-null  object
 4   horario                 603215 non-null  object
 5   uf                      603215 non-null  object
 6   br                      601867 non-null  float64
 7   km                      601867 non-null  object
 8   municipio               603215 non-null  object
 9   causa_principal         603215 non-null  object
 10  causa_acidente          603215 non-null  object
 11  ordem_tipo_acidente     603215 non-null  int64
 12  tipo_acidente           603215 non-null  object
 13  classificacao_acidente  603212 non-null  object
 14  fase_dia                603215 non-null  object
 15  sentido_via             603215 non-null  object
 16  condicao_metereologica  603215 non-null  object
 17  tipo_pista              603215 non-null  object
 18  tracado_via             603215 non-null  object
 19  uso_solo                603215 non-null  object
 20  id_veiculo              583643 non-null  float64
 21  tipo_veiculo            583643 non-null  object
 22  marca                   603215 non-null  object
 23  ano_fabricacao_veiculo  583643 non-null  float64
 24  tipo_envolvido          545574 non-null  object
 25  estado_fisico           545574 non-null  object
 26  idade                   493807 non-null  float64
 27  sexo                    545574 non-null  object
 28  ilesos                  545574 non-null  float64
 29  feridos_leves           545574 non-null  float64
 30  feridos_graves          545574 non-null  float64
 31  mortos                  545574 non-null  float64
 32  latitude                603215 non-null  float64
 33  longitude               603215 non-null  float64
 34  regional                603188 non-null  object
 35  delegacia               603032 non-null  object
 36  uop                     601552 non-null  object
dtypes: float64(12), int64(1), object(24)
memory usage: 170.3+ MB

In [ ]:
acidentes24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196306 entries, 0 to 196305
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      196306 non-null  float64
 1   pesid                   196306 non-null  int64
 2   data_inversa            196306 non-null  object
 3   dia_semana              196306 non-null  object
 4   horario                 196306 non-null  object
 5   uf                      196306 non-null  object
 6   br                      196306 non-null  int64
 7   km                      196306 non-null  object
 8   municipio               196306 non-null  object
 9   causa_acidente          196306 non-null  object
 10  tipo_acidente           196306 non-null  object
 11  classificacao_acidente  196303 non-null  object
 12  fase_dia                196306 non-null  object
 13  sentido_via             196306 non-null  object
 14  condicao_metereologica  196306 non-null  object
 15  tipo_pista              196306 non-null  object
 16  tracado_via             196306 non-null  object
 17  uso_solo                196306 non-null  object
 18  id_veiculo              196306 non-null  int64
 19  tipo_veiculo            189729 non-null  object
 20  marca                   196306 non-null  object
 21  ano_fabricacao_veiculo  196306 non-null  int64
 22  tipo_envolvido          179114 non-null  object
 23  estado_fisico           179114 non-null  object
 24  idade                   196306 non-null  int64
 25  sexo                    179114 non-null  object
 26  ilesos                  196306 non-null  int64
 27  feridos_leves           196306 non-null  int64
 28  feridos_graves          196306 non-null  int64
 29  mortos                  196306 non-null  int64
 30  latitude                196306 non-null  float64
 31  longitude               196306 non-null  float64
 32  regional                196295 non-null  object
 33  delegacia               196229 non-null  object
 34  uop                     195931 non-null  object
dtypes: float64(3), int64(9), object(23)
memory usage: 52.4+ MB

In [ ]:
datatran24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73156 entries, 0 to 73155
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      73156 non-null  float64
 1   data_inversa            73156 non-null  object
 2   dia_semana              73156 non-null  object
 3   horario                 73156 non-null  object
 4   uf                      73156 non-null  object
 5   br                      73156 non-null  int64
 6   km                      73156 non-null  object
 7   municipio               73156 non-null  object
 8   causa_acidente          73156 non-null  object
 9   tipo_acidente           73156 non-null  object
 10  classificacao_acidente  73155 non-null  object
 11  fase_dia                73156 non-null  object
 12  sentido_via             73156 non-null  object
 13  condicao_metereologica  73156 non-null  object
 14  tipo_pista              73156 non-null  object
 15  tracado_via             73156 non-null  object
 16  uso_solo                73156 non-null  object
 17  pessoas                 73156 non-null  int64
 18  mortos                  73156 non-null  int64
 19  feridos_leves           73156 non-null  int64
 20  feridos_graves          73156 non-null  int64
 21  ilesos                  73156 non-null  int64
 22  ignorados               73156 non-null  int64
 23  feridos                 73156 non-null  int64
 24  veiculos                73156 non-null  int64
 25  latitude                73156 non-null  float64
 26  longitude               73156 non-null  float64
 27  regional                73153 non-null  object
 28  delegacia               73120 non-null  object
 29  uop                     73044 non-null  object
dtypes: float64(3), int64(9), object(18)
memory usage: 16.7+ MB

In [ ]:
acidentes_todas_causas_tipos25.head(5)

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,652468,1467636.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Não Informado,0.0,0.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
1,652468,1467635.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Feminino,0.0,1.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
2,652468,1467634.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Masculino,0.0,1.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
3,652468,1467637.0,2025-01-01,quarta-feira,00:30:00,PE,101.0,"89,5",JABOATAO DOS GUARARAPES,Sim,...,Não Informado,0.0,0.0,0.0,0.0,"-8,20760697","-34,98372005",SPRF-PE,DEL01-PE,UOP01-DEL01-PE
4,652469,1467628.0,2025-01-01,quarta-feira,00:50:00,SC,101.0,120,ITAJAI,Sim,...,Feminino,0.0,1.0,0.0,0.0,"-26,912758","-48,711998",SPRF-SC,DEL04-SC,UOP04-DEL04-SC

In [ ]:
acidentes25.head(5)

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,652493,1467686,2025-01-01,quarta-feira,06:20:00,SP,116,225,GUARULHOS,Reação tardia ou ineficiente do condutor,...,Não Informado,0,0,0,0,"-23,48586772","-46,54075317",SPRF-SP,DEL01-SP,UOP01-DEL01-SP
1,652519,1467833,2025-01-01,quarta-feira,07:50:00,CE,116,"546,2",PENAFORTE,Pista esburacada,...,Masculino,1,0,0,0,"-7,812288","-39,08333306",SPRF-CE,DEL05-CE,UOP03-DEL05-CE
2,652522,1468042,2025-01-01,quarta-feira,08:45:00,PR,369,"88,2",CORNELIO PROCOPIO,Reação tardia ou ineficiente do condutor,...,Masculino,1,0,0,0,"-23,182565","-50,637228",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
3,652544,1467849,2025-01-01,quarta-feira,11:00:00,PR,116,74,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,...,Masculino,1,0,0,0,"-25,36517687","-49,04223028",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
4,652549,1467791,2025-01-01,quarta-feira,09:30:00,MG,251,471,FRANCISCO SA,Velocidade Incompatível,...,Masculino,1,0,0,0,"-16,46801304","-43,43121303",SPRF-MG,DEL12-MG,UOP01-DEL12-MG

In [ ]:
datatran25.head(5)

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,652493,2025-01-01,quarta-feira,06:20:00,SP,116,225,GUARULHOS,Reação tardia ou ineficiente do condutor,Tombamento,...,0,0,1,1,2,"-23,48586772","-46,54075317",SPRF-SP,DEL01-SP,UOP01-DEL01-SP
1,652519,2025-01-01,quarta-feira,07:50:00,CE,116,"546,2",PENAFORTE,Pista esburacada,Colisão frontal,...,0,1,4,1,6,"-7,812288","-39,08333306",SPRF-CE,DEL05-CE,UOP03-DEL05-CE
2,652522,2025-01-01,quarta-feira,08:45:00,PR,369,"88,2",CORNELIO PROCOPIO,Reação tardia ou ineficiente do condutor,Colisão traseira,...,0,2,0,3,2,"-23,182565","-50,637228",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
3,652544,2025-01-01,quarta-feira,11:00:00,PR,116,74,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,...,0,4,0,1,2,"-25,36517687","-49,04223028",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
4,652549,2025-01-01,quarta-feira,09:30:00,MG,251,471,FRANCISCO SA,Velocidade Incompatível,Colisão frontal,...,1,1,2,2,4,"-16,46801304","-43,43121303",SPRF-MG,DEL12-MG,UOP01-DEL12-MG

In [ ]:
acidentes_todas_causas_tipos_PRF = pd.concat([acidentes_todas_causas_tipos24, acidentes_todas_causas_tipos25, acidentes_todas_causas_tipos26], ignore_index=True)
acidentes_PRF = pd.concat([acidentes24, acidentes25, acidentes26], ignore_index=True)
datatran_PRF = pd.concat([datatran24, datatran25, datatran26], ignore_index=True)

In [ ]:
acidentes_todas_causas_tipos_PRF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1238682 entries, 0 to 1238681
Data columns (total 37 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   id                      1238682 non-null  float64
 1   pesid                   1119627 non-null  float64
 2   data_inversa            1238682 non-null  object
 3   dia_semana              1238682 non-null  object
 4   horario                 1238682 non-null  object
 5   uf                      1238682 non-null  object
 6   br                      1235859 non-null  float64
 7   km                      1235859 non-null  object
 8   municipio               1238682 non-null  object
 9   causa_principal         1238682 non-null  object
 10  causa_acidente          1238682 non-null  object
 11  ordem_tipo_acidente     1238682 non-null  int64
 12  tipo_acidente           1238682 non-null  object
 13  classificacao_acidente  1238552 non-null  object
 14  fase_dia                1238682 non-null  object
 15  sentido_via             1238682 non-null  object
 16  condicao_metereologica  1238682 non-null  object
 17  tipo_pista              1238682 non-null  object
 18  tracado_via             1238682 non-null  object
 19  uso_solo                1238682 non-null  object
 20  id_veiculo              1199083 non-null  float64
 21  tipo_veiculo            1199083 non-null  object
 22  marca                   1238682 non-null  object
 23  ano_fabricacao_veiculo  1199083 non-null  float64
 24  tipo_envolvido          1119627 non-null  object
 25  estado_fisico           1119627 non-null  object
 26  idade                   1015516 non-null  float64
 27  sexo                    1119627 non-null  object
 28  ilesos                  1119627 non-null  float64
 29  feridos_leves           1119627 non-null  float64
 30  feridos_graves          1119627 non-null  float64
 31  mortos                  1119627 non-null  float64
 32  latitude                1238682 non-null  object
 33  longitude               1238682 non-null  object
 34  regional                1238633 non-null  object
 35  delegacia               1238291 non-null  object
 36  uop                     1236552 non-null  object
dtypes: float64(10), int64(1), object(26)
memory usage: 349.7+ MB

In [ ]:
acidentes_todas_causas_tipos_PRF.head(5)

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_principal,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,571772.0,1268971.0,2024-01-01,segunda-feira,00:05:00,RJ,101.0,"272,5",TANGUA,Sim,...,Masculino,0.0,0.0,0.0,1.0,-22.72936,-42.701125,SPRF-RJ,DEL02-RJ,UOP03-DEL02-RJ
1,571774.0,1268985.0,2024-01-01,segunda-feira,00:05:00,GO,153.0,"424,6",ANAPOLIS,Não,...,Feminino,1.0,0.0,0.0,0.0,-16.229185,-49.009797,SPRF-GO,DEL02-GO,UOP01-DEL02-GO
2,571774.0,1268985.0,2024-01-01,segunda-feira,00:05:00,GO,153.0,"424,6",ANAPOLIS,Sim,...,Feminino,1.0,0.0,0.0,0.0,-16.229185,-49.009797,SPRF-GO,DEL02-GO,UOP01-DEL02-GO
3,571777.0,1269020.0,2024-01-01,segunda-feira,01:45:00,ES,101.0,"264,1",SERRA,Sim,...,Masculino,1.0,0.0,0.0,0.0,-20.172928,-40.267364,SPRF-ES,DEL02-ES,UOP01-DEL02-ES
4,571778.0,1269028.0,2024-01-01,segunda-feira,00:45:00,SC,101.0,110,PENHA,Não,...,Masculino,1.0,0.0,0.0,0.0,-26.83477,-48.706151,SPRF-SC,DEL03-SC,UOP02-DEL03-SC

In [ ]:
acidentes_PRF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407276 entries, 0 to 407275
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      407276 non-null  float64
 1   pesid                   407276 non-null  int64
 2   data_inversa            407276 non-null  object
 3   dia_semana              407276 non-null  object
 4   horario                 407276 non-null  object
 5   uf                      407276 non-null  object
 6   br                      407276 non-null  int64
 7   km                      407276 non-null  object
 8   municipio               407276 non-null  object
 9   causa_acidente          407276 non-null  object
 10  tipo_acidente           407276 non-null  object
 11  classificacao_acidente  407261 non-null  object
 12  fase_dia                407276 non-null  object
 13  sentido_via             407276 non-null  object
 14  condicao_metereologica  407276 non-null  object
 15  tipo_pista              407276 non-null  object
 16  tracado_via             407276 non-null  object
 17  uso_solo                407276 non-null  object
 18  id_veiculo              407276 non-null  int64
 19  tipo_veiculo            393906 non-null  object
 20  marca                   407276 non-null  object
 21  ano_fabricacao_veiculo  407276 non-null  int64
 22  tipo_envolvido          371725 non-null  object
 23  estado_fisico           371725 non-null  object
 24  idade                   407276 non-null  int64
 25  sexo                    371725 non-null  object
 26  ilesos                  407276 non-null  int64
 27  feridos_leves           407276 non-null  int64
 28  feridos_graves          407276 non-null  int64
 29  mortos                  407276 non-null  int64
 30  latitude                407276 non-null  object
 31  longitude               407276 non-null  object
 32  regional                407253 non-null  object
 33  delegacia               407113 non-null  object
 34  uop                     406757 non-null  object
dtypes: float64(1), int64(9), object(25)
memory usage: 108.8+ MB

In [ ]:
datatran_PRF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151486 entries, 0 to 151485
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      151486 non-null  float64
 1   data_inversa            151486 non-null  object
 2   dia_semana              151486 non-null  object
 3   horario                 151486 non-null  object
 4   uf                      151486 non-null  object
 5   br                      151486 non-null  int64
 6   km                      151486 non-null  object
 7   municipio               151486 non-null  object
 8   causa_acidente          151486 non-null  object
 9   tipo_acidente           151486 non-null  object
 10  classificacao_acidente  151483 non-null  object
 11  fase_dia                151486 non-null  object
 12  sentido_via             151486 non-null  object
 13  condicao_metereologica  151486 non-null  object
 14  tipo_pista              151486 non-null  object
 15  tracado_via             151486 non-null  object
 16  uso_solo                151486 non-null  object
 17  pessoas                 151486 non-null  int64
 18  mortos                  151486 non-null  int64
 19  feridos_leves           151486 non-null  int64
 20  feridos_graves          151486 non-null  int64
 21  ilesos                  151486 non-null  int64
 22  ignorados               151486 non-null  int64
 23  feridos                 151486 non-null  int64
 24  veiculos                151486 non-null  int64
 25  latitude                151486 non-null  object
 26  longitude               151486 non-null  object
 27  regional                151479 non-null  object
 28  delegacia               151425 non-null  object
 29  uop                     151332 non-null  object
dtypes: float64(1), int64(9), object(20)
memory usage: 34.7+ MB

In [ ]:
output_path = '/content/drive/MyDrive/Data/PRF/'
acidentes_todas_causas_tipos_PRF.to_csv(output_path + 'acidentes_todas_causas_tipos_PRF.csv', index=False)
acidentes_PRF.to_csv(output_path + 'acidentes_PRF.csv', index=False)
datatran_PRF.to_csv(output_path + 'datatran_PRF.csv', index=False)